config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'recipes#index'
  get 'pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  mount_uploader :image, ImageUploader
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Montserrat" rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>RecipeDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div style="position: relative;left: 46%;"> 
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <a class="button" <%= link_to "Recipe App", root_path, class: 'navbar-brand' %></a></div>
     <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="navbar-nav navbar-right">
         <li><%= link_to "About", pages_about_path %></li>
       </ul>
     </div>
   </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page Placeholder</h1>

app/views/recipes/_form.html.erb
<div class="container-fluid">
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <p>Choose a cover image</p>
      <%= form.file_field :image %>
      <% if @recipe.image? %>
       <%= image_tag @recipe.image.url, class: "recipe-show" %>
       <%= form.check_box :remove_image %>
         Remove Image
     <% end %>
    </div>
  <div class="form-group">
     <%= form.label :title %>
     <%= form.text_field :title, id: :recipe_title, class: "form-control" %>
   </div>


   <div class="form-group">
     <%= form.label :description %>
     <%= form.text_area :description, id: :recipe_description, class: "form-control" %>
   </div>


   <div class="form-group">
     <h2>Ingredients</h2>
       <%= form.nested_fields_for :ingredients do |ingredient| %>
         <%= ingredient.text_field :content %>
         <%= ingredient.remove_nested_fields_link 'Remove', class: 'btn', role: 'button'%>
       <% end %>
         <%= form.add_nested_fields_link :ingredients, 'Add ingredient', class:'button' , role: 'button'%>
   </div>


     <div class="form-group">
       <h2>Steps</h2>
         <%= form.nested_fields_for :steps do |step| %>
           <%= step.text_field :direction %>
           <%= step.remove_nested_fields_link 'Remove', class:'btn', role: 'button' %>
         <% end %>
           <%= form.add_nested_fields_link :steps, 'Add Step', class:'button', role: 'button'%>
     </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
<%= render 'form', recipe: @recipe %>
<br>
<div class="button__group">
  <a class="button" data-filter="filter 1" <%= link_to 'Show', @recipe %></a>
  <a class="button" data-filter="filter 2" <%= link_to 'Back', recipes_path %></a>
</div>


</div>
</div>
</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>
<br>
<div class="container-fluid">
        <div class="row">
            <% @recipes.each do |recipe| %>
          <div class="col-md-4">
            <div class="recipe-box">
              <% if recipe.image? %>
              <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
              <% end %>
                  <h3 class="card-title"><%= recipe.title %></h3>
                    <h4 class="card-text"><%= recipe.description %></h4>
                    <div class="button__group">
                      <a class="button" data-filter="filter 1" <%= link_to 'Show', recipe %></a>
                        <a class="button" data-filter="filter 2" <%= link_to 'Edit', edit_recipe_path(recipe) %></a>
                        <a class="button" data-filter="filter 3" <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></a>
                </div><!--button_group-->
              </div><!--recipe-box-->
        </div><!-- col-md-4-->
    <% end %>
    </div><!-- row -->
<br>
<div class="button__group">
  <a class="button" data-filter="filter 1" <%= link_to 'New Recipe', new_recipe_path %></a>
</div>

</div>

app/views/recipes/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>
<br>
<div class="button__group">
  <a class="button" data-filter="filter 1" <<%= link_to 'Back', recipes_path %></a>
</div>

</div>
</div>
</div>

app/views/recipes/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

<p id="notice"><%= notice %></p>
<% if @recipe.image? %>
<%= image_tag @recipe.image.url, class: "recipe-show" %>
<% end %>
  <h2>
  <%= @recipe.title %>
</h2>
<p>
  <%= @recipe.description %>
</p>

<h3>Ingredients</h3>
  <ul>
    <% for @ingredient in @recipe.ingredients %>
    <li><%= @ingredient.content %></li>
    <% end %>
  </ul>

<h3>Steps</h3>
  <ol>
    <% for @step in @recipe.steps %>
    <li><%= @step.direction %></li>
    <% end %>
  </ol>
  <div class="button__group">
    <a class="button" data-filter="filter 1" <%= link_to 'Edit', edit_recipe_path(@recipe) %></a>
    <a class="button" data-filter="filter 2" <%= link_to 'Back', recipes_path %></a>
  </div>
</div>
</div>
</div>